language: go

go:
  - "1.13.x"
  - "1.14.x"
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify
  - go get github.com/tidwall/gjson
  
after_success:
  - goveralls -service=travis-ci
